
import logging
from unicodedata import category

from requests import session
from app.schemas.session_schema import UserSession
from app.llm.prompt_builder import PromptBuilder
from app.llm.openai_client import classify_problem, chat
from app.config.settings import settings

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# CATEGORY CONSTANTS — exact TYPE names from MUFU Brain doc
# Order matters — numeric selection maps by index (1 = first item)
# ---------------------------------------------------------------------------
CATEGORIES = [
    "TYPE_1_PLATFORM_DEPENDENCY",   
    "TYPE_2_LOCAL_VISIBILITY",    
    "TYPE_3_LOW_MARGIN",            
    "TYPE_4_RETENTION",             
    "TYPE_5_DIGITAL_CHAOS",       
    "TYPE_6_LAUNCH",                
    "OTHER",                      
]

# Human-readable labels shown in the menu — matches MUFU Brain doc exactly
CATEGORY_LABELS = {
    "TYPE_1_PLATFORM_DEPENDENCY":  "1 Too dependent on platforms (Uber, Deliveroo...)",
    "TYPE_2_LOCAL_VISIBILITY":     "2 Not enough customers / lack of visibility (social media)",
    "TYPE_3_LOW_MARGIN":           "3 I'm making sales but not enough profit (margins)",
    "TYPE_4_RETENTION":            "4 Customers come but don't come back",
    "TYPE_5_DIGITAL_CHAOS":        "5 I have lots of tools but it's chaotic",
    "TYPE_6_LAUNCH":               "6 I'm launching / relaunching a location",
    "OTHER":                       "7 Something else",
}

# Keywords that suggest the user is describing multiple problems
MULTIPLE_PROBLEMS_KEYWORDS = [
    "several", "multiple", "many", "few", "couple",
    "two", "three", "and also", "as well", "plus",
    "both", "all of", "everything",
]

# Keywords for yes/no confirmation
AFFIRMATIVES = {
    "yes", "yeah", "correct", "right", "yep", "sure",
    "ok", "okay", "exactly", "that's it", "thats it",
    "confirmed", "absolutely", "definitely", "true",
}
NEGATIVES = {
    "no", "nope", "not really", "wrong", "incorrect",
    "not quite", "not exactly", "different", "other",
}


class ProblemDetectionWorkflow:

    # -----------------------------------------------------------------------
    # STEP 1: Build and return the problem menu message
    # Called when entering PROBLEM_DETECTION stage.
    # -----------------------------------------------------------------------
    async def get_category_menu_message(self, session: UserSession) -> str:
        """
        Generates a warm intro (LLM) + deterministic numbered menu.
        The menu is always the same — only the intro is personalized.
        """
        owner_name = session.profile.get("owner_name", "")
        restaurant_name = session.profile.get("restaurant_name", "your restaurant")

        # LLM writes a short warm bridge sentence before the menu
        system = PromptBuilder.problem_detection_system_prompt(session)
        messages = PromptBuilder.build_messages(
            system_prompt=system,
            history=session.history,
            user_input=(
                f"Write exactly one short warm sentence thanking {owner_name} and "
                f"confirming you've noted the info on {restaurant_name}. "
                "Then ask what their biggest problem is right now. "
                "Do NOT include the menu — I will append it."
            ),
        )
        intro = await chat(
            messages=messages,
            model=settings.OPENAI_MODEL,
            max_tokens=80,
            temperature=0.7,
        )

        # Deterministic menu — never generated by LLM
        menu_lines = [f"{label}" for label in CATEGORY_LABELS.values()]
        menu = "\n".join(menu_lines)

        return f"{intro}\n\n{menu}\n\nReply with a number or describe your problem in your own words."

    # -----------------------------------------------------------------------
    # STEP 2: Parse the user's reply to the menu
    # Returns (category, needs_confirmation, reply_message)
    # -----------------------------------------------------------------------
    async def process_problem_input(
        self, session: UserSession, user_input: str
    ) -> tuple[str | None, bool, str]:
        """
        Handles all three input types from the MUFU Brain doc:

        Returns:
            category         → detected category string or None
            needs_clarification → True if user said "several problems"
            message          → the message to send back to the user
        """
        # ── Case 1: Numeric selection ────────────────────────────────────────
        category = self._parse_numeric(user_input)
        if category:
            logger.info(f"[{session.user_id}] Numeric selection → {category}")
            # Numeric = direct map, skip confirmation per doc rules
            confirm_msg = await self._build_transition_message(session, category)
            return category, False, confirm_msg

        # ── Ca se 2: Multiple problems ────────────────────────────────────────
        if self._mentions_multiple_problems(user_input):
            logger.info(f"[{session.user_id}] Multiple problems detected")
            msg = await self._ask_priority_problem(session)
            return None, True, msg

        # ── Case 3: Free text → LLM classifies ──────────────────────────────
        category = await classify_problem(user_input, CATEGORIES)
        if category not in CATEGORIES:
            category = "OTHER"
        logger.info(f"[{session.user_id}] Free text classified → {category}")

        # Rephrase and confirm per doc: "If I understand correctly..."
        confirm_msg = await self._build_confirmation_message(session, user_input, category)
        return category, False, confirm_msg

    # -----------------------------------------------------------------------
    # STEP 3: Handle category confirmation (CATEGORY_CONFIRMATION stage)
    # -----------------------------------------------------------------------
    async def handle_confirmation(
        self, session: UserSession, user_input: str
    ) -> tuple[bool, str]:
        """
        User is confirming or rejecting the detected category.

        Returns:
            confirmed → True if user said yes
            message   → next message to send
        """
        text = user_input.lower().strip()
        numeric_category = self._parse_numeric(user_input)
        if numeric_category:
            session.category = numeric_category
            msg = await self._build_transition_message(session, numeric_category)
            return True, msg

        if any(word in text for word in AFFIRMATIVES):
            logger.info(f"[{session.user_id}] Category confirmed: {session.category}")
            # Per MUFU Brain doc: "OK [First Name], I'll help you with this.
            # I have a few quick questions..."
            msg = await self._build_transition_message(session, session.category)
            return True, msg

        if any(word in text for word in NEGATIVES):
            logger.info(f"[{session.user_id}] Category rejected — re-asking")
            # Go back and re-show the menu
            msg = await self.get_category_menu_message(session)
            return False, msg

        # Ambiguous — treat as a new free-text description and re-classify
        logger.info(f"[{session.user_id}] Ambiguous confirmation — re-classifying")
        category = await classify_problem(user_input, CATEGORIES)
        if category not in CATEGORIES:
            category = "OTHER"
        session.category = category
        confirm_msg = await self._build_confirmation_message(session, user_input, category)
        return False, confirm_msg

    # -----------------------------------------------------------------------
    # PRIVATE HELPERS
    # -----------------------------------------------------------------------

    def _parse_numeric(self, user_input: str) -> str | None:
        """
        Maps '1' → CATEGORIES[0], '2' → CATEGORIES[1], etc.
        Returns None if input is not a valid number.
        """
        try:
            idx = int(user_input.strip()) - 1
            if 0 <= idx < len(CATEGORIES):
                return CATEGORIES[idx]
        except ValueError:
            pass
        return None

    def _mentions_multiple_problems(self, user_input: str) -> bool:
        """
        Detects if user is describing several problems at once.
        Per MUFU Brain doc: ask them to pick the priority one.
        """
        text = user_input.lower()
        return any(kw in text for kw in MULTIPLE_PROBLEMS_KEYWORDS)

    async def _ask_priority_problem(self, session: UserSession) -> str:
        """
        Per MUFU Brain doc exact script:
        'I understand, they're often related. But if you had to choose just
        one to address as a priority right now, which one would it be?'
        LLM personalizes the tone while keeping the core message.
        """
        system = PromptBuilder.problem_detection_system_prompt(session)
        messages = PromptBuilder.build_messages(
            system_prompt=system,
            history=session.history,
            user_input=(
                "The user mentioned several problems. Write a short empathetic message "
                "acknowledging that problems are often related, then ask them to pick "
                "just ONE priority to address right now. Keep it under 2 sentences. "
                "Then append the menu options again."
            ),
        )
        reply = await chat(
            messages=messages,
            model=settings.OPENAI_MODEL,
            max_tokens=120,
            temperature=0.6,
        )

        # Always append the deterministic menu after the LLM message
        menu_lines = [f"{label}" for label in CATEGORY_LABELS.values()]
        menu = "\n".join(menu_lines)
        return f"{reply}\n\n{menu}"

    async def _build_confirmation_message(
        self, session: UserSession, user_input: str, category: str
    ) -> str:
        """
        Per MUFU Brain doc: rephrase detected problem and ask for confirmation.
        Script: 'If I understand correctly, your main problem is [rephrasing].
        Is that right?'
        """
        label = CATEGORY_LABELS.get(category, category)
        system = PromptBuilder.problem_detection_system_prompt(session)
        messages = PromptBuilder.build_messages(
            system_prompt=system,
            history=session.history,
            user_input=(
                f"The user said: '{user_input}'. "
                f"You've detected their main problem as: '{label}'. "
                "Rephrase their problem back to them in one empathetic sentence "
                "and ask if that's correct. "
                "Format: 'If I understand correctly, [rephrase]. Is that right?'"
            ),
        )
        return await chat(
            messages=messages,
            model=settings.OPENAI_MODEL,
            max_tokens=100,
            temperature=0.6,
        )

    async def _build_transition_message(
    self, session: UserSession, category: str
) -> str:
        owner_name = session.profile.get("owner_name", "")
        label = CATEGORY_LABELS.get(category, "your situation")  # use category here

        system = PromptBuilder.problem_detection_system_prompt(session)
        messages = PromptBuilder.build_messages(
            system_prompt=system,
            history=session.history,
            user_input=(
                f"Write the transition message to {owner_name} confirming you'll help "
                f"with: '{label}'. "     
                "Tell them you have a few quick questions to fully understand their "
                "situation before giving concrete recommendations. "
                "Ask if they're ready to get started. Keep it under 3 sentences. "
                "Be warm and encouraging."
            ),
        )
        
        return await chat(
            messages=messages,
            model=settings.OPENAI_MODEL,
            max_tokens=100,
            temperature=0.7,
        )